apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app-server
  name: app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app-server
    spec:
      containers:
        - image: yabuchan905/sample-app-server
          name: app-server
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
