apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web-server
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: web-server
    spec:
      containers:
        - env:
            - name: VITE_APP_API_ROOT
              value: http://app-server:8080
          image: yabuchan905/sample-web-server
          name: web-server
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
